trigger:
  branches:
    include:
    - master

pr: none

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

jobs:
- job: Test

  pool:
    vmImage: "ubuntu-18.04"

  strategy:
    matrix:
      Python37:
        pythonVersion: "3.7"
      Python38:
        pythonVersion: "3.8"

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: "$(pythonVersion)"
      displayName: "Use Python $(pythonVersion)"

    - task: Cache@2
      inputs:
        key: "pip | $(Agent.OS) | requirements.txt"
        restoreKeys:
          pip | $(Agent.OS)
      displayName: "Cache pip dependencies"

    - bash: scripts/install
      displayName: "Install dependencies"

    - bash: scripts/test
      displayName: "Run tests"
