---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish to PyPI"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: scripts/install
      - name: "Build package artifacts"
        run: scripts/build
      - name: "Publish to PyPI"
        run: scripts/publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
